global:
  WS:
    title: 'Wandering Soul'
    color: 'LIGHT_PURPLE'
  Help:
    cmd: 'h'
    title: 'Help Channel'
    color: 'YELLOW'
    bracketcolor: 'GOLD'
  debate:
    title: 'Debate Channel'
  Staff:
    title: "Staff Channel"
    color: 'DARK_PURPLE'
    staff: true
    bold: true
    cmd: 'tm'
  ST:
    title: 'Story Team'
    color: 'DARK_GREEN'
    staff: true
    bold: true
  Dev:
    title: 'Development Team'
    color: 'GOLD'
    staff: true
    bold: true
  Mod:
    title: 'Moderation Team'
    color: 'DARK_AQUA'
    staff: true
    bold: true
  C:
    title: 'Community Team'
    color: 'LIGHT_PURPLE'
    cmd: 'ct'
    staff: true
    bold: true
  A:
    title: 'Admin Channel'
    color: 'DARK_RED'
    staff: true
    bold: true

local:
  rp:
    title: 'Roleplay'
    color: 'DARK_GREEN'
    tag: ''
    radius: 20
    looc:
      tag: 'LOOC'
      cooldown: 6
  W:
    title: 'Whisper'
    color: 'BLUE'
    radius: 3
    looc:
      tag: 'w-OOC'
      cmd: 'wooc'
      cooldown: 6
  Quiet:
    title: 'Undertone'
    color: 'AQUA'
    radius: 8
    cmd: 'q'
    looc:
      tag: 'Q-OOC'
      cmd: 'qooc'
      cooldown: 6
  Shout:
    cmd: 's'
    color: 'RED'
    radius: 48
    looc:
      tag: 'S-OOC'
      cmd: 'sooc'
      cooldown: 15
  leb:
    color: 'DARK_GREEN'
    bracketcolor: 'GREEN'
    radius: 100
    tag: 'Local Event'
    cmd: 'leb'
    title: 'Local Event Broadcast'
  loom:
    color: 'BLUE'
    bracketcolor: 'DARK_BLUE'
    radius: 36
    tag: 'Local Moderator'
    cmd: 'loom'
    title: 'Local Moderator'

broadcast:
  Broadcast:
    cmd: 'bc'
    color: 'YELLOW'
  EventBC:
    cmd: 'ebc'
    title: 'Event Broadcast'
    tag: 'Event'
    color: 'DARK_GREEN'
  StaffBC:
    cmd: 'sbc'
    tag: 'Staff Broadcast'
    color: 'RED'
    signname: true
    textcolor: 'YELLOW'