name: NativeChat
main: me.lotc.chat.NativeChat
version: 1.0.1
api-version: 1.13
depend: [Tythan, LuckPerms]
softdepend: [ArcheCore, Omniscience]
description: LotC's \#1 draw!
author: Awe

commands:
  chat:
    description: Command for all chat and channel interaction
    permission: chat.command

permissions:
  chat.emotecolor:
    description: Allows you to customize the color of your emotes
  chat.markdown:
    description: Lets you use inbuilt markdown formatting for bold and italic RP text
  chat.nocooldown:
    description: Cooldown timers set by channels do not apply
    default: op